name: 'Publish the documentation website artifact'
on: [ workflow_call ]

concurrency:
  group: publish-website
  cancel-in-progress: false

jobs:
  publish:
    if: github.repository == 'infix-de/testBalloon'

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 'Deploy uploaded artifact to GitHub Pages'
        id: deployment
        uses: actions/deploy-pages@v4
