name: 'Build the doc site'

on: [ workflow_call, workflow_dispatch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out the project'
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
        with:
          gradle-cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: 'Setup Python'
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: 'Install mkdocs-material'
        run: pip install mkdocs-material mkdocs-material[imaging]

      - name: 'Generate API reference'
        run: ./gradlew dokkaGenerateHtml

      - name: 'Build doc site'
        run: ./gradlew docSiteBuild

      - name: 'Upload doc site'
        uses: actions/upload-pages-artifact@v3
        with:
          path: documentation/site/build
