name: 'Publish the documentation website artifact'
on: [ workflow_call ]

concurrency:
  group: publish-website
  cancel-in-progress: false

jobs:
  publish:
    if: github.event.repository.fork == false

    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 'Deploy artifact to GitHub Pages'
        id: deployment
        # https://github.com/actions/deploy-pages/releases
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
